### ISSUE TITLE
caja-extensions can not show proper language in guix system.

### ISSUE THREAD

**Issue by tumashu** [mate-desktop/caja-extensions#109]
https://github.com/mate-desktop/caja-extensions/commit/86d43b190d57402a7e531a8079f90b52bc83567f

This commit let caja-extensions in guix can not show proper language, 
for example: show "Chinese" when LC_ALL=zh_CN.UTF8,  when I revert this commit and try again,
the problem disapear.

guix system do not use "/usr/share/locale/".

**Comment by cwendling** [comment]
I'm curious what was the rationale for that commit, because indeed it's kind of bound to cause this kind of problems… @rbuj do you remember? Note that what it removes is *not* a problem in a library, it's not forcing the active domain but setting details on a specific one.

**Comment by rbuj** [comment]
The internationalization for libraries works differently from how you do it for applications. https://docs.gtk.org/glib/i18n.html

i18n for libraries only require two sentences:
```
#define GETTEXT_PACKAGE "???"
#include <glib/gi18n-lib.h> 
```

**Comment by rbuj** [comment]
@cwendling since the location of the po file cannot be resolved you can revert the commit, leaving bindtextdomain and bind_textdomain_codeset function calls as before merging it.

> For a library, you only have to call bindtextdomain() and bind_textdomain_codeset() in your initialization function. If your library doesn’t have an initialization function, you can call the functions before the first translated message.

https://docs.gtk.org/glib/i18n.html

**Comment by cwendling** [comment]
> The internationalization for libraries works differently from how you do it for applications. […]

Yes, but as your second quote states, you still need to call `bindtextdomain()` (which maps a domain to where the translations are located) and `bind_textdomain_codeset()` (which declares the codeset for that specific domain) early in your setup.

**Comment by rbuj** [comment]
There is no problem fetching the messages from the catalog on ubuntu, debian, fedora... imho it's a portability issue. Note bind_textdomain_codeset isn't mandatory. However, since we only provide the catalogs with UTF-8 codeset it's logical to force their coding.

https://www.gnu.org/software/gettext/manual/html_node/Libraries.html

**Comment by cwendling** [comment]
Well in practice AFAIK if not set explicitly it will use the system locale encoding (or no conversion at all?), so 99% of the time it'll be fine anyway, but it's more correct to declare it.
This said, I'm not 100% sure what would happen here, because we need UTF-8 no matter the system encoding for all GTK strings… meh, then again it's probably not really change anything on any reasonable system.

**Comment by cwendling** [comment]
OK I checked now I'm on the computer, and it defines the *output* encoding for the strings returned by gettext, so indeed we want it to be UTF-8 all the time for strings passed to GTK.
It however defaults to the locale encoding, which is likely to be UTF-8 already for reasonable systems, so again, 99.99% of the time it's gonna be correct without it, but it's safer to call it.
